[package]
name = "rust-sqlite-tests"
version = "0.1.0"
authors = ["Sean McLoughlin <smcloughlin1015@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlite = "0.24.0"